### ISSUE TITLE
change in BNL's ARK-based URLs

### ISSUE THREAD

**Issue by mromanello** [impresso/impresso-text-acquisition#103]
(to be fixed by August 31, 2020)

- “ark:/70795” becomes “ark:70795”, the rest of the ARK remains unchanged;
- https://iiif1.eluxemburgensia.lu/iiif/2/ -> https://iiif.eluxemburgensia.lu/image/iiif/2/
- The ARK still has to be encoded using %2f instead of slashes

**Comment by mromanello** [comment]
Update: this has been hot-fixed in the dev and prod DBs (see code in this [notebook](https://github.com/impresso/impresso-master-db/blob/master/notebooks/update-iiif-links-Lux.ipynb)), but it still needs to be fixed in the BNL importer as well as in the canonical data.

**Comment by piconti** [comment]
After further checking of the problem with @e-maud, we identified that the wrong links remain the Solr, but that the correct ones are fetched from the DB for the interface. 
As a result, we will not reingest the BNL data to fix this issue for the end of 2023 baby release. 
Rather, the canonical data will be patched to correct the URLs to prevent unnecessary large re-processing.

**Comment by piconti** [comment]
Update: 
Following the data sharing meeting with BNL, we now know that they have new OCR for their entire collection, including the data that we already had during Impresso 1. 
Since the issue was patched in the DBs, that it currently works and that this patch/update would not impact the enrichment processing tasks (only the iiif links would be modified), it was decided that it would **not** be changed in the current canonical data before the Dec. 2023 release, and instead fully re-ingested once the updated orignal data dfrom BNL is available.

However, the number of CIs in the current data will still be checked, to verify it's coherent with the statistics computed by Matteo in Sept. 2020.
