### ISSUE TITLE
[BNF importer] invalid issue JSON output

### ISSUE THREAD

**Issue by mromanello** [impresso/impresso-text-acquisition#104]
There are two problems here:
1. `iiif_link` should contain the link to JSON manifest, not to the JPG image itself;
2. the coordinates field `c` is missing for content items of type `image` (e.g. `excelsior-1910-11-16-a-i0161`).

Both problems will break the `impress-pyimages` script that downloads images via IIIF, cfr. https://github.com/impresso/impresso-images/blob/89bef72675f4bd9ea9a7557cbbadcf337c61a0bf/impresso-pyimages/impresso_images/data_utils.py#L62

**Original JSON**:
```json
// taken from s3://original-canonical-staging/excelsior/issues/excelsior-1910-issues.jsonl.bz2
{
      "m": {
        "id": "excelsior-1910-11-16-a-i0161",
        "tp": "image",
        "pp": [
          12
        ],
        "t": "Publicité",
        "iiif_link": "https://gallica.bnf.fr/iiif/ark:/12148/bpt6k46000007/f12/2753,4963,3010,3273/full/0/default.jpg"
      }
    }
```

**Expected JSON**:
```json
    {
      "m": {
        "id": "excelsior-1910-11-16-a-i0161",
        "tp": "image",
        "pp": [
          12
        ],
        "t": "Publicité",
        "iiif_link": "https://gallica.bnf.fr/iiif/ark:/12148/bpt6k46000007/f12/info.json",
        "c": [
          2753,
          4963,
          3010,
          3273
        ]
      },
}
```

**Comment by piconti** [comment]
This issue is linked to issue #105, and BNF-EN importer is also concerned.

1. For all 3 importer, `iiif_link` contains the link to the JPG image itself.
2. The placement of `iiif_link` and `c` in the content items fileds is inconsistent accross importers. 

While `iiif_link` is expected to be in the subfield `m` by the rebuilder [[see here]](https://github.com/impresso/impresso-pycommons/blob/f6a6c5511c35ad6094d60906706169063e7979d4/impresso_commons/text/rebuilder.py#L219), it's not the case for the coordinates `c` which are expected to be ouside of the subfield.

As a result, the placements of the subfields were uniformized to fit the requirements of the rebuilder for now, and will be corrected along with the rebuilder so that each module (and importer) can be tested independently first.
This correction should take place BEFORE a reingestion of the data corresponding to the concerned importers (BNF, BNF-EN, RERO).
