### ISSUE TITLE
missing content items compared with alpha/beta releases

### ISSUE THREAD

**Issue by e-maud** [impresso/impresso-text-acquisition#51]
While doing the collection sync Daniele noticed that some ci are missing. He's keeping track of them. Examples:
```
EXP-1888-08-15-a-i0002
EXP-1917-07-14-a-i0027
EXP-1917-07-14-a-i0094
EXP-1917-07-14-a-i0096
EXP-1917-07-14-a-i0098
EXP-1935-11-26-a-i0056
EXP-1935-11-26-a-i0062
EXP-1935-11-26-a-i0063
EXP-1935-11-26-a-i0067
EXP-1935-11-26-a-i0081
EXP-1935-11-26-a-i0082
EXP-1954-01-29-a-i0009
EXP-1954-01-29-a-i0199
EXP-1959-11-19-a-i0003
EXP-1965-01-04-a-i0042
EXP-1965-01-04-a-i0043
EXP-1965-01-04-a-i0045
```

I checked in  `/original-canonical-data-publrelease`, and it seems that the page files are empty for the issues of these items:
`s3cmd ls s3://original-canonical-data-publrelease/EXP/pages/EXP-1888/* | more`
(pages are 14 KB)

cf: 
- https://impresso.slack.com/archives/CK5RM0R9P/p1564644643050300
- https://impresso.slack.com/archives/CK5RM0R9P/p1564645566057900

**Comment by mromanello** [comment]
I've been working a bit on this. I did a systematic scan of all pages bz2 archives in S3 for the newspapers that were in @danieleguido 's list, looking for the empty ones (~70 issues in total, out of ~140k checked). Here the count of impacted issues per year per newspaper:

```python
{
    'EXP': {
        1779: 2,
        1823: 50,
        1824: 1,
        1888: 1,
        1896: 1,
        1898: 1,
        1917: 1,
        1935: 1,
        1954: 1,
        1959: 1,
        1965: 1,
        1994: 1,
        1995: 2,
        1997: 1,
        2001: 1,
        2010: 1,
        2012: 1
    },
    'GDL': {
        1881: 3,
        1917: 1,
        1951: 2,
        1969: 1,
        1979: 1
    }
}
```

Since @ehoelzl is currently re-running a local ingestion (not immediately written to s3) of RERO-1 newspaper, we will be able to check whether the impacted issues are ok (have pages in the bz2) or not. If this check is positive, we will put back the corrupted bz2 archives in s3.  

@ehoelzl This is the more precise list with issue ids instead of counts:

```python
{'EXP': {1779: ['EXP-1779-03-28-a', 'EXP-1779-11-06-a'], 1823: ['EXP-1823-01-13-a', 'EXP-1823-01-20-a', 'EXP-1823-01-27-a', 'EXP-1823-02-03-a', 'EXP-1823-02-10-a', 'EXP-1823-02-17-a', 'EXP-1823-02-24-a', 'EXP-1823-03-03-a', 'EXP-1823-03-10-a', 'EXP-1823-03-17-a', 'EXP-1823-03-24-a', 'EXP-1823-03-31-a', 'EXP-1823-04-07-a', 'EXP-1823-04-14-a', 'EXP-1823-04-21-a', 'EXP-1823-04-28-a', 'EXP-1823-05-05-a', 'EXP-1823-05-12-a', 'EXP-1823-05-19-a', 'EXP-1823-05-26-a', 'EXP-1823-06-02-a', 'EXP-1823-06-09-a', 'EXP-1823-06-16-a', 'EXP-1823-06-23-a', 'EXP-1823-06-30-a', 'EXP-1823-07-07-a', 'EXP-1823-07-14-a', 'EXP-1823-07-21-a', 'EXP-1823-07-28-a', 'EXP-1823-08-04-a', 'EXP-1823-08-18-a', 'EXP-1823-08-25-a', 'EXP-1823-09-01-a', 'EXP-1823-09-08-a', 'EXP-1823-09-15-a', 'EXP-1823-09-22-a', 'EXP-1823-09-29-a', 'EXP-1823-10-06-a', 'EXP-1823-10-13-a', 'EXP-1823-10-20-a', 'EXP-1823-10-27-a', 'EXP-1823-11-03-a', 'EXP-1823-11-10-a', 'EXP-1823-11-17-a', 'EXP-1823-11-24-a', 'EXP-1823-12-01-a', 'EXP-1823-12-08-a', 'EXP-1823-12-15-a', 'EXP-1823-12-22-a', 'EXP-1823-12-29-a'], 1824: ['EXP-1824-01-02-a'], 1888: ['EXP-1888-08-15-a'], 1896: ['EXP-1896-09-05-a'], 1898: ['EXP-1898-06-14-a'], 1917: ['EXP-1917-07-14-a'], 1935: ['EXP-1935-11-26-a'], 1954: ['EXP-1954-01-29-a'], 1959: ['EXP-1959-11-19-a'], 1965: ['EXP-1965-01-04-a'], 1994: ['EXP-1994-11-17-a'], 1995: ['EXP-1995-02-01-a', 'EXP-1995-08-09-a'], 1997: ['EXP-1997-05-30-a'], 2001: ['EXP-2001-09-03-a'], 2010: ['EXP-2010-10-01-a'], 2012: ['EXP-2012-01-07-a']}, 'GDL': {1881: ['GDL-1881-02-26-a', 'GDL-1881-02-28-a', 'GDL-1881-03-01-a'], 1917: ['GDL-1917-06-15-a'], 1951: ['GDL-1951-01-18-a', 'GDL-1951-01-19-a'], 1969: ['GDL-1969-06-23-a'], 1979: ['GDL-1979-04-10-a']}}
```

**Comment by mromanello** [comment]
After investigating this issue quite a bit, it turns out that:
- we are probably looking at two different issues
- where one are empty bz2 archives in s3
- and the other are content items missing from MySQL, but probably due to an ingestion problem

As for the first issue (empty bz2 archives) it's not a problem of S3, but rather a problem with the data (e.g. unreadable archives). After checking the output of the new refactored Olive imported, the list of items in my previous comment is found in the list of failed issues, so it's all good (they will be imported into MySQL but with the `is_damaged` flag.

As for the second issue, more work/debugging is necessary (planned for the public release).
