### ISSUE TITLE
Missing articles in BNL

### ISSUE THREAD

**Issue by simon-clematide** [impresso/impresso-text-acquisition#79]
The original from Luxembourg has all articles:
http://www.eluxemburgensia.lu/BnlViewer/view/index.html?lang=fr#panel:pp|issue:2345212|page:7

However, we https://impresso-project.ch/app/issue/dunioun-1947-08-02-a/page/dunioun-1947-08-02-a-p0007/article/dunioun-1947-08-02-a-i0009 have 2 parts missing with German text if you enable the grids you can see it easily. I checked in rebuilt. It is not there. I checked in canonical, and there the text is actually there, but it has no pOf attribute.
[dunioun-1947-08-02-a-pages.json.txt](https://github.com/impresso/impresso-text-acquisition/files/4124825/dunioun-1947-08-02-a-pages.json.txt)

The issue file does not contain it.
[dunioun-1947-08-02-a.issue.json.txt](https://github.com/impresso/impresso-text-acquisition/files/4124875/dunioun-1947-08-02-a.issue.json.txt)

On the same issue, more articles are missing. Maybe it is related to relatively complex structured articles
https://impresso-project.ch/app/issue/dunioun-1947-08-02-a/page/dunioun-1947-08-02-a-p0004

**Comment by mromanello** [comment]
Many thanks for flagging this up, @simon-clematide !

After inspecting the problem with @ehoelzl and @e-maud, it turns out this is due to the fact that sections in BNL data are semantically somehow underspecified: there are sections that act as containers of other articles or ads, and sections that constitute instead what we would simply consider a CI with type `article`.

A heuristic to distinguish between the two types is that the former does not have a `body`, while the latter does. 

@ehoelzl will try to fix this problem without altering **all** canonical ids for BNL. Specifically, we will keep unchanged ids that are not part of sections; those that are part of an article-like section will be merged into a new canonical item, and its new ID will not interfere with the legacy ones. In doing this we will keep the mapping between old canonical IDs that get merged and the ID of the new item (so that we can automatically "repair" user collections containing any of the items affected).

(@e-maud @ehoelzl please do correct me should I have mis-reported something)

More generally, a **question** still remains open for me: do we want to keep information about logical sections of a newspaper in our canonical scheme? For some newspapers we do have this information, but we don't use it currently. If we do, then we also need to think how to display this information to the user in the interface.

**Comment by ehoelzl** [comment]
The bug has been fixed in the following way:
- Ingestion is done exactly as before in the beginning
- Then, the importer fetches all the sections and keeps only sections that validate all of the following conditions: 
      - Section has a `BODY` AND
      - All other direct child divs are articles (to make sure this isn't the Obituary or Advertisement section)

When all of those sections are fetched, they merge all the articles that belong to them, while removing the corresponding content items. This mechanism allows us to keep the same canonical-id for all CIs, but remove CIs that are within sections.

Another bug was noticed, which is that advertisements appear both as `ad` and `image`, but they should only be `ad`. So all those duplicates are removed, and canonical ids remain consistent with potentially new ones and deleted ones.

This means that any content item that is in the old BNL data and in the new one will be the same.
